import { NextRequest, NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(req: NextRequest) {
  try {
    const { name, email, discussion } = await req.json();

    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    const mailOptions = {
      from: email,
      to: process.env.EMAIL_USER,
      subject: 'New Contact Form Submission',
      html: `
        <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; padding: 20px;">
          <div style="text-align: center; margin-bottom: 20px;">
            <img src="https://www.onsense.ai/logo.png" alt="Company Logo" style="max-width: 150px; max-width: 50px;" />
          </div>
          <h2 style="text-align: center; color: #0052FF; margin-bottom: 30px;">New Contact Form Submission</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="font-weight: bold; padding: 10px; border: 1px solid #ddd; width: 50%;">Name:</td>
              <td style="padding: 10px; border: 1px solid #ddd; width: 50%;">${name}</td>
            </tr>
            <tr>
              <td style="font-weight: bold; padding: 10px; border: 1px solid #ddd;">Email:</td>
              <td style="padding: 10px; border: 1px solid #ddd;">${email}</td>
            </tr>
            <tr>
              <td style="font-weight: bold; padding: 10px; border: 1px solid #ddd;">Discussion:</td>
              <td style="padding: 10px; border: 1px solid #ddd;">${discussion}</td>
            </tr>
          </table>
          <p style="text-align: center; margin-top: 30px; font-size: 0.9em; color: #777;">
            This email was generated by the contact form. Please do not reply directly to this email.
          </p>
        </div>
      `,
    };    

    await transporter.sendMail(mailOptions);

    return NextResponse.json({ message: 'Email sent successfully' });
  } catch (error) {
    console.error('Error sending email:', error);
    return NextResponse.json(
      { message: 'Failed to send email' },
      { status: 500 }
    );
  }
}
